# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_social_addthis', '0004_auto_20161014_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='This setting can only be set once per page. If set twice, it will be overridden.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='body'),
        ),
    ]
